/**
* @File Name : JobPositionController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : September 12, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | September 12, 2025 |   | Initial Version
**/

public class JobPositionController {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}